services:
  api:
    build: .
    container_name: musicapi-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: musicapi
      DB_USER: postgres
      DB_PASSWORD: postgres
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: musicapi
      JWT_SECRET: local-dev-secret-change-me-local-dev-secret-change-me
      CORS_ALLOWED_ORIGINS: http://localhost:5500,http://127.0.0.1:5500
      APP_INTEGRADOR_REGIONAIS_URL: https://integrador-argus-api.geia.vip/v1/regionais
    depends_on:
      - postgres
      - minio
    restart: unless-stopped

  postgres:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    container_name: musicapi-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: musicapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: public.ecr.aws/docker/library/adminer:latest
    container_name: musicapi-adminer
    ports:
      - "5050:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: musicapi-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data:
  postgres_data:
